[project]
name = "dftml"
description = "Benchmarking ML models for predicting band gap of 2D material from formula only"
version = "67"
requires-python = ">=3.8.10" # Because ASDRP server have 3.8.10
readme = "README.md"

dependencies = [
  "pandas",
  "numpy",
  "scikit-learn",
  "scikit-optimize",
  "matplotlib",
  "xgboost",
  "pyarrow",
  "ase"
]

[project.optional-dependencies]
dev = [
  "pip-review"
]

[tool.ruff]
indent-width = 2
line-length = 80
fix = true
