[project]
name = "dftml"
description = "Benchmarking ML models for predicting band gap of 2D material without CBM & VBM"
version = "67"
dependencies = [
  "pandas",
  "numpy",
  "scikit-learn",
  "scikit-optimize",
  "matplotlib",
  "xgboost",
]
requires-python = "<=3.8.10" # Because ASDRP server have 3.8.10
readme = "README.md"

[tool.ruff]
indent-width = 2
line-length = 80
fix = true
